package pl.lab2PPS.hibernate;
// Generated 2020-04-21 13:48:50 by Hibernate Tools 4.3.1



/**
 * Kategorie generated by hbm2java
 */
public class Kategorie  implements java.io.Serializable {


     private Integer id;
     private Podkategorie podkategorie;
     private String nazwa;

    public Kategorie() {
    }

    public Kategorie(Podkategorie podkategorie, String nazwa) {
       this.podkategorie = podkategorie;
       this.nazwa = nazwa;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Podkategorie getPodkategorie() {
        return this.podkategorie;
    }
    
    public void setPodkategorie(Podkategorie podkategorie) {
        this.podkategorie = podkategorie;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }




}


