package pl.lab2PPS.hibernate;
// Generated 2020-04-21 13:48:50 by Hibernate Tools 4.3.1



/**
 * Podkategorie generated by hbm2java
 */
public class Podkategorie  implements java.io.Serializable {


     private Integer id;
     private int idKategorii;
     private String nazwa;
     private Kategorie kategorie;

    public Podkategorie() {
    }

	
    public Podkategorie(int idKategorii, String nazwa) {
        this.idKategorii = idKategorii;
        this.nazwa = nazwa;
    }
    public Podkategorie(int idKategorii, String nazwa, Kategorie kategorie) {
       this.idKategorii = idKategorii;
       this.nazwa = nazwa;
       this.kategorie = kategorie;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdKategorii() {
        return this.idKategorii;
    }
    
    public void setIdKategorii(int idKategorii) {
        this.idKategorii = idKategorii;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public Kategorie getKategorie() {
        return this.kategorie;
    }
    
    public void setKategorie(Kategorie kategorie) {
        this.kategorie = kategorie;
    }




}


