package pl.lab2PPS.hibernate;
// Generated 2020-04-21 13:48:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Propozycja generated by hbm2java
 */
public class Propozycja  implements java.io.Serializable {


     private Integer id;
     private Set wiadomoscs = new HashSet(0);
     private Set zgloszenies = new HashSet(0);

    public Propozycja() {
    }

    public Propozycja(Set wiadomoscs, Set zgloszenies) {
       this.wiadomoscs = wiadomoscs;
       this.zgloszenies = zgloszenies;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Set getWiadomoscs() {
        return this.wiadomoscs;
    }
    
    public void setWiadomoscs(Set wiadomoscs) {
        this.wiadomoscs = wiadomoscs;
    }
    public Set getZgloszenies() {
        return this.zgloszenies;
    }
    
    public void setZgloszenies(Set zgloszenies) {
        this.zgloszenies = zgloszenies;
    }




}


