package pl.lab2PPS.hibernate;
// Generated 2020-04-21 13:48:50 by Hibernate Tools 4.3.1



/**
 * Uzytkownik generated by hbm2java
 */
public class Uzytkownik  implements java.io.Serializable {


     private Integer id;
     private String nick;
     private String mail;
     private String haslo;
     private int uprawnienia;
     private Integer XLokalizacja;
     private Integer YLokalizacja;

    public Uzytkownik() {
    }

	
    public Uzytkownik(String nick, String mail, String haslo, int uprawnienia) {
        this.nick = nick;
        this.mail = mail;
        this.haslo = haslo;
        this.uprawnienia = uprawnienia;
    }
    public Uzytkownik(String nick, String mail, String haslo, int uprawnienia, Integer XLokalizacja, Integer YLokalizacja) {
       this.nick = nick;
       this.mail = mail;
       this.haslo = haslo;
       this.uprawnienia = uprawnienia;
       this.XLokalizacja = XLokalizacja;
       this.YLokalizacja = YLokalizacja;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getHaslo() {
        return this.haslo;
    }
    
    public void setHaslo(String haslo) {
        this.haslo = haslo;
    }
    public int getUprawnienia() {
        return this.uprawnienia;
    }
    
    public void setUprawnienia(int uprawnienia) {
        this.uprawnienia = uprawnienia;
    }
    public Integer getXLokalizacja() {
        return this.XLokalizacja;
    }
    
    public void setXLokalizacja(Integer XLokalizacja) {
        this.XLokalizacja = XLokalizacja;
    }
    public Integer getYLokalizacja() {
        return this.YLokalizacja;
    }
    
    public void setYLokalizacja(Integer YLokalizacja) {
        this.YLokalizacja = YLokalizacja;
    }




}


