package pl.lab2PPS.hibernate;
// Generated 2020-04-21 13:48:50 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Wiadomosc generated by hbm2java
 */
public class Wiadomosc  implements java.io.Serializable {


     private Integer id;
     private Propozycja propozycja;
     private String wiadomosc;
     private Date data;

    public Wiadomosc() {
    }

    public Wiadomosc(Propozycja propozycja, String wiadomosc, Date data) {
       this.propozycja = propozycja;
       this.wiadomosc = wiadomosc;
       this.data = data;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Propozycja getPropozycja() {
        return this.propozycja;
    }
    
    public void setPropozycja(Propozycja propozycja) {
        this.propozycja = propozycja;
    }
    public String getWiadomosc() {
        return this.wiadomosc;
    }
    
    public void setWiadomosc(String wiadomosc) {
        this.wiadomosc = wiadomosc;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }




}


