package pl.lab2PPS.hibernate;
// Generated 2020-04-21 13:48:50 by Hibernate Tools 4.3.1



/**
 * Zgloszenie generated by hbm2java
 */
public class Zgloszenie  implements java.io.Serializable {


     private Integer id;
     private Propozycja propozycja;
     private String tesc;

    public Zgloszenie() {
    }

    public Zgloszenie(Propozycja propozycja, String tesc) {
       this.propozycja = propozycja;
       this.tesc = tesc;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Propozycja getPropozycja() {
        return this.propozycja;
    }
    
    public void setPropozycja(Propozycja propozycja) {
        this.propozycja = propozycja;
    }
    public String getTesc() {
        return this.tesc;
    }
    
    public void setTesc(String tesc) {
        this.tesc = tesc;
    }




}


